export enum actionTypes {
  ADD_NOTE = 'ADD_NOTE',
  SWAP_NOTE = 'SWAP_NOTE',
  UPDATE_NOTE = 'UPDATE_NOTE',
  DELETE_NOTE = 'DELETE_NOTE',
  // loading
  LOAD_NOTES = 'LOAD_NOTES',
  LOAD_NOTES_SUCCESS = 'LOAD_NOTES_SUCCESS',
  LOAD_NOTES_ERROR = 'LOAD_NOTES_ERROR',
  // syncing
  SYNC_NOTES = 'SYNC_NOTES',
  SYNC_NOTES_SUCCESS = 'SYNC_NOTES_SUCCESS',
  SYNC_NOTES_ERROR = 'SYNC_NOTES_ERROR',
}
