export enum actionTypes {
  // note operations
  ADD_NOTE = 'ADD_NOTE',
  SWAP_NOTE = 'SWAP_NOTE',
  UPDATE_NOTE = 'UPDATE_NOTE',
  DELETE_NOTE = 'DELETE_NOTE',
  // loading notes
  LOAD_NOTES = 'LOAD_NOTES',
  LOAD_NOTES_SUCCESS = 'LOAD_NOTES_SUCCESS',
  LOAD_NOTES_ERROR = 'LOAD_NOTES_ERROR',

  // category operations
  ADD_CATEGORY = 'ADD_CATEGORY',
  SWAP_CATEGORY = 'SWAP_CATEGORY',
  UPDATE_CATEGORY = 'UPDATE_CATEGORY',
  DELETE_CATEGORY = 'DELETE_CATEGORY',
  // loading categories
  LOAD_CATEGORIES = 'LOAD_CATEGORIES',
  LOAD_CATEGORIES_SUCCESS = 'LOAD_CATEGORIES_SUCCESS',
  LOAD_CATEGORIES_ERROR = 'LOAD_CATEGORIES_ERROR',

  // syncing state
  SYNC_STATE = 'SYNC_STATE',
  SYNC_STATE_SUCCESS = 'SYNC_STATE_SUCCESS',
  SYNC_STATE_ERROR = 'SYNC_STATE_ERROR',
}
